### ISSUE TITLE
re-arrange yaml to have OS on top instead of 'architectures'

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#51]

**Comment by kmturley** [comment]
I think many properties could be reordered how you would read a plugin page e.g.
https://studiorack.github.io/studiorack-site/instruments/surge-synthesizer/surge

**Before (alphabetical)**
```
---
audio: https://open-audio-stack.github.io/open-audio-stack-registry/plugins/surge-synthesizer/surge/surge.flac
author: Surge Synth Team
changes: |
  - Fix a logic error in creating Surge XT folder in new session
  - Add 1.3.3 cherry pick list and bump cmakelist version
  - Update tempo after patch load and calculate time_data.ppqPos
  - Update LFO and Step Seq presets to have the LFO EG enabled
date: '2024-08-11T00:00:00.000Z'
description: Hybrid synthesizer featuring many synthesis techniques, a great selection
  of filters, a flexible modulation engine, a smorgasbord of effects, and modern features
  like MPE and microtuning.
files:
  - architectures:
      - x64
    contains:
      - elf
      - clap
      - lv2
      - vst3
    format: zip
    sha256: dd431b75f5fa197c4bffa6ca27ca46970f0a94c834119bb1db7decdeec4c28db
    systems:
      - type: linux
    size: 97294804
    type: archive
    url: https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.4/surge-xt-linux-1.3.4-pluginsonly.tar.gz
  - architectures:
      - arm64
      - x64
    contains:
      - app
      - clap
      - component
      - vst3
    format: zip
    sha256: 37d8d809693adc86587b7bc75a2384fc4e905f259aa9b9a21777749d36fbf8aa
    systems:
      - type: mac
    size: 186958216
    type: archive
    url: https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.4/surge-xt-macos-1.3.4-pluginsonly.zip
  - architectures:
      - x64
    contains:
      - exe
      - clap
      - vst3
    format: zip
    sha256: 564e162c560af07ad4ed47fe1bfcd827cf97a575de30d06c48249aad2e7c35e6
    systems:
      - type: win
    size: 49093875
    type: archive
    url: https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.4/surge-xt-win64-1.3.4-pluginsonly.zip
image: https://open-audio-stack.github.io/open-audio-stack-registry/plugins/surge-synthesizer/surge/surge.jpg
license: gpl-3.0
name: Surge XT
tags:
  - Instrument
  - Synth
  - Modulation
type: instrument
url: https://github.com/surge-synthesizer/surge
```

**After (readable)**
```
---
name: Surge XT
author: Surge Synth Team
description: Hybrid synthesizer featuring many synthesis techniques, a great selection
  of filters, a flexible modulation engine, a smorgasbord of effects, and modern features
  like MPE and microtuning.
license: gpl-3.0
type: instrument
tags:
  - Instrument
  - Synth
  - Modulation
url: https://github.com/surge-synthesizer/surge
audio: https://open-audio-stack.github.io/open-audio-stack-registry/plugins/surge-synthesizer/surge/surge.flac
image: https://open-audio-stack.github.io/open-audio-stack-registry/plugins/surge-synthesizer/surge/surge.jpg
date: '2024-08-11T00:00:00.000Z'
changes: |
  - Fix a logic error in creating Surge XT folder in new session
  - Add 1.3.3 cherry pick list and bump cmakelist version
  - Update tempo after patch load and calculate time_data.ppqPos
  - Update LFO and Step Seq presets to have the LFO EG enabled
files:
  - systems:
      - type: linux
    architectures:
      - x64
    contains:
      - elf
      - clap
      - lv2
      - vst3
    format: zip
    type: archive
    sha256: dd431b75f5fa197c4bffa6ca27ca46970f0a94c834119bb1db7decdeec4c28db
    size: 97294804
    url: https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.4/surge-xt-linux-1.3.4-pluginsonly.tar.gz
  - systems:
      - type: mac
    architectures:
      - arm64
      - x64
    contains:
      - app
      - clap
      - component
      - vst3
    format: zip
    type: archive
    sha256: 37d8d809693adc86587b7bc75a2384fc4e905f259aa9b9a21777749d36fbf8aa
    size: 186958216
    url: https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.4/surge-xt-macos-1.3.4-pluginsonly.zip
  - systems:
      - type: win
    architectures:
      - x64
    contains:
      - exe
      - clap
      - vst3
    sha256: 564e162c560af07ad4ed47fe1bfcd827cf97a575de30d06c48249aad2e7c35e6
    size: 49093875
    type: archive
    format: zip
    url: https://github.com/surge-synthesizer/releases-xt/releases/download/1.3.4/surge-xt-win64-1.3.4-pluginsonly.zip
```
